server:
    port: 8909
spring:
    profiles: eurekaclient
    application:
        name: guozhiyang-test
eureka:
    client:
        service-url:
            defaultZone: http://localhost:7001/eureka/
