spring:
    profiles:
        active:
            dev
---
spring:
    profiles: dev
    application:
        name: microservicecloud-config-atguigu-dev
user:
    name: xiaohua
---
spring:
    profiles: test
    application:
        name: microservicecloud-config-atguigu-test
